-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS 'YEAR'
    , DATE_FORMAT(SALES_DATE, '%m') AS 'MONTH'
    , GENDER
    , COUNT(DISTINCT A.USER_ID) AS 'USERS'
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
AND GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE, '%Y'), DATE_FORMAT(SALES_DATE, '%m'), GENDER
ORDER BY 1,2,3