SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO T1, (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS COUNT
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) T2
WHERE T1.FOOD_TYPE = T2.FOOD_TYPE AND T1.FAVORITES = T2.COUNT
ORDER BY T1.FOOD_TYPE DESC