SELECT DECODE(TO_CHAR(START_DATE, 'MM'), '08', 8, '09', 9, 10) AS MONTH
    , CAR_ID
    , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE TO_CHAR(START_DATE, 'MM') BETWEEN '08' AND '10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND TO_CHAR(START_DATE, 'MM') BETWEEN '08' AND '10'
GROUP BY DECODE(TO_CHAR(START_DATE, 'MM'), '08', 8, '09', 9, 10), CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC