-- 코드를 입력하세요
SELECT A.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(B.PRICE*S.SALES) AS 'TOTAL_SALES'
FROM AUTHOR A, BOOK B, BOOK_SALES S
WHERE A.AUTHOR_ID = B.AUTHOR_ID
AND B.BOOK_ID = S.BOOK_ID
AND DATE_FORMAT(S.SALES_DATE, '%Y%m') = '202201'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC