WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM 
    UNION ALL
    SELECT NUM+1 FROM CTE
    WHERE NUM < 23
)

SELECT CTE.NUM, COUNT(HOUR(A.DATETIME))
FROM CTE
LEFT JOIN ANIMAL_OUTS AS A
ON CTE.NUM = HOUR(A.DATETIME)
GROUP BY CTE.NUM

